// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvjfwtkcymxyftcmynbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2amZ3dGtjeW14eWZ0Y215bmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Nzc0OTYsImV4cCI6MjA2NDI1MzQ5Nn0.YlKF1ngzN20HzQLGBrcBv4J-dE0rlu2deFKGK_z_eN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});